jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     -name:  Checkout Repository 
     uses: actions/checkout@v4
     
     -name: Set up Java 17
     uses: actions/setup-java@v4
      with:
       distibution: 'temurin'
       java-version: '17'
     -name: Build  Application
       run:
         cd app/user-service
        ./mvnw clean package -DskipTests
     -name: Build docker image
     run:
       cd app/user-service
       docker build -t user-service
